### PR TITLE
Create Destination.cpp

### PR DESCRIPTION
**Pull request by AhmedHamdyKotp**
informing that all classes "Airline, Activity, and Hotel" should contains the "TODO" constructors and functions that i mentioned

### CODE REVIEW

**Comment by OsamaAshraf01** [comment]
Make them 😊😊

**Comment by AhmedHamdyKotp** [comment]
> Make them 😊😊

Broo, they are not my classes 🤡

**Comment by OsamaAshraf01** [comment]
🤦‍♂️🤦‍♂️

**Comment by OsamaAshraf01** [comment]
then, ask your teammates to make them

**Pull request closed without merging**
