### PR TITLE
Update currencies.csv

### PR DESCRIPTION
**Pull request by AhmedHamdyKotp**

### CODE REVIEW

**Comment by OsamaAshraf01** [comment]
Great work, but please always provide a comment in your pull requests that describes why you changed anything.

**Comment by OsamaAshraf01** [comment]
Why did you update this file?

**Review by OsamaAshraf01 — COMMENTED** [review]
Why did you update this file?

**Comment by AhmedHamdyKotp** [comment]
> Why did you update this file?

Brooo, since when that 1 dollar equal .02 EGP 😂😂
+ the identifier of the logic it self does not exist "USD 1 "

**Comment by OsamaAshraf01** [comment]
We meant that 1 EGP = 0.02 USD

**Comment by OsamaAshraf01** [comment]
No difference

**Comment by OsamaAshraf01** [comment]
But I can't see 'EGP' in the new file.

**Review by AhmedHamdyKotp — COMMENTED** [review]
Here it is

**Comment by AhmedHamdyKotp** [comment]
> No difference

☠️

**Comment by OsamaAshraf01** [comment]
yastaaaa, since when 1 EGP = 47 USD 😂

**Comment by AhmedHamdyKotp** [comment]
> yastaaaa, since when 1 EGP = 47 USD 😂

Look at convert method u will know
🤠

**Comment by OsamaAshraf01** [comment]
Okay great job, but use dot instead of comma in last line

**Comment by AhmedHamdyKotp** [comment]
Be in known that thus is USD via any currency and vise versa only

**Pull request merged**
